default: data_pre_process filter_reformat

data_pre_process: data_pre_process.F90
	f95 -o data_pre_process data_pre_process.F90

filter_reformat: filter_reformat.F90
	f95 -o filter_reformat filter_reformat.F90
